apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: <app-name>
  name: <app-name>
spec:
  replicas: 2
  selector:
    matchLabels:
      run: <app-name>
  template:
    metadata:
      labels:
        run: <app-name>
    spec:
      containers:
      - image: gcr.io/<google-project-id>/<app-name>:latest
        name: <app-name>
        ports:
        - containerPort: <container-port>
